export { fetchMovies } from './fetchMovies'
export { fetchMovie } from './fetchMovie'
export { setLoading } from './setLoading'
export { updateSearch } from './updateSearch'
export { setPage } from './setPage'
export { fetchConfig } from './fetchConfig'
export { toggleMovieFav } from './toggleMovieFav'
